
export const LOAD_CUSTOMERS_START = "LOAD_CUSTOMERS_START";
export const LOAD_CUSTOMERS_SUCCESS = "LOAD_CUSTOMERS_SUCESS";
export const LOAD_CUSTOMERS_ERROR = "LOAD_CUSTOMERS_ERROR";

export const LOAD_CUSTOMER_START = "LOAD_CUSTOMER_START"
export const LOAD_CUSTOMER_SUCCESS = "LOAD_CUSTOMER_SUCCESS"
export const LOAD_CUSTOMER_ERROR = "LOAD_CUSTOMER_ERROR"

export const ADD_CUSTOMER_START = "ADD_CUSTOMER_START";
export const ADD_CUSTOMER_SUCCESS = "ADD_CUSTOMER_SUCESS";
export const ADD_CUSTOMER_ERROR = "ADD_CUSTOMER_ERROR";

export const UPDATE_CUSTOMER_START = "UPDATE_CUSTOMER_START";
export const UPDATE_CUSTOMER_SUCCESS = "UPDATE_CUSTOMER_SUCESS";
export const UPDATE_CUSTOMER_ERROR = "UPDATE_CUSTOMER_ERROR";

export const DELETE_CUSTOMER_START = "DELETE_CUSTOMER_START";
export const DELETE_CUSTOMER_SUCCESS = "DELETE_CUSTOMER_SUCESS";
export const DELETE_CUSTOMER_ERROR = "DELETE_CUSTOMER_ERROR";

