
export const LOAD_HOMES_START = "LOAD_HOMES_START";
export const LOAD_HOMES_SUCCESS = "LOAD_HOMES_SUCESS";
export const LOAD_HOMES_ERROR = "LOAD_HOMES_ERROR";

export const LOAD_HOME_START = "LOAD_HOME_START"
export const LOAD_HOME_SUCCESS = "LOAD_HOME_SUCCESS"
export const LOAD_HOME_ERROR = "LOAD_HOME_ERROR"

export const ADD_HOME_START = "ADD_HOME_START";
export const ADD_HOME_SUCCESS = "ADD_HOME_SUCESS";
export const ADD_HOME_ERROR = "ADD_HOME_ERROR";

export const UPDATE_HOME_START = "UPDATE_HOME_START";
export const UPDATE_HOME_SUCCESS = "UPDATE_HOME_SUCESS";
export const UPDATE_HOME_ERROR = "UPDATE_HOME_ERROR";

export const DELETE_HOME_START = "DELETE_HOME_START";
export const DELETE_HOME_SUCCESS = "DELETE_HOME_SUCESS";
export const DELETE_HOME_ERROR = "DELETE_HOME_ERROR";

